language: php
php:
 - '5.6'
 - '7.2'
 - nightly

before_script:
 - composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
